<?
$this->layout()->setVariables([
    'title'    => '¿Quiéres colaborar?',
])
?>
<p>
    ¿Estás interesado en colaborar? Los aportes que podemos recibir son:
</p>

<center>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- horizontal-content -->
    <ins class="adsbygoogle"
         style="display:inline-block;width:728px;height:90px"
         data-ad-client="ca-pub-4234050867741816"
         data-ad-slot="1596749955"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</center>
<ul>
    <li>Apoyo técnico: todo el código del proyecto es público y se puede ver, editar y mejorar en el portal de
    github en <a href="https://github.com/transparentegt/portal" >transparente.gt</a></li>

    <li>Tareas específicas: los pendientes por hacer son varios, en especial a estas alturas del proyecto. Llevamos
    un manejador de incidencias de estas tareas específicas, las cuales se pueden ver en el
    <a href="https://github.com/transparentegt/portal/issues?state=open" >manejador de incidencias</a></li>

    <li>Donaciones económicas: a pesar que el proyecto está creado por voluntariado que aporta su tiempo libre para la
    investigación y creación de este, se tienen gastos para contratar el servicio de alojamiento, compra del dominio y
    demás que están pendientes. Cualquier donación es bienvenida.

    </li>
</ul>

<div class="row">
    <div class="col-md-6">
        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title">Banco Industrial</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <img class="img-thumbnail" src="http://www.skysatelital.net/wp-content/uploads/2012/02/Banco-Industrial1.jpg" />
                <dl class="dl-horizontal">
                    <dt>Nombre en la cuenta</dt> <dd>Stuardo Rodríguez</dd>
                    <dt>Tipo de  cuenta</dt>     <dd>monetaria</dd>
                    <dt>Cuenta en quetzales</dt> <dd>02-7013-7935</dd>
                    <dt>Cuenta en dólares</dt>   <dd>02-7077-8779</dd>
                </dl>
            </div><!-- /.box-body -->

        </div>
    </div>
    <div class="col-md-6">
        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title">Banco G&amp;T</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <img style="margin-bottom: 30px;" class="img-thumbnail" src="http://www.radiosdeguate.com/images/bancos/BANCO%20G&T%20CONTINENTAL.gif" />
                <dl class="dl-horizontal">
                    <dt>Nombre en la cuenta</dt> <dd>Stuardo Rodríguez</dd>
                    <dt>Tipo de  cuenta</dt>     <dd>ahorros</dd>
                    <dt>Cuenta en quetzales</dt> <dd>2-1018538-3</dd>
                </dl>
            </div><!-- /.box-body -->

        </div>
    </div>
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title">Internacionales / tarjeta de crédito</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <p>
                    Para las personas que están fuera de Guatemala, o que se les facilita realizar las donaciones por medio
                    de tarjeta de crédito, podemos recibir su colaboración por medio de Paypal.
                </p>
                <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" class="text-center">
                    <input type="hidden" name="cmd" value="_s-xclick">
                    <input type="hidden" name="hosted_button_id" value="48SXBFDP69SP2">
                    <input type="image" src="https://www.paypalobjects.com/es_ES/ES/i/btn/btn_donateCC_LG.gif" name="submit" alt="PayPal. La forma rápida y segura de pagar en Internet.">
                    <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
                </form>
            </div><!-- /.box-body -->
        </div>
    </div>
</div>

<center>
    <a href="/contact" class="btn btn-lg btn-warning">¿Quieres ponerte en contacto con nosotros? Click aquí para contactarnos.</a>
</center>