<?
$this->layout()->setVariables([
    'title'    => 'dbCompras',
    'subtitle' => 'proyecto de <a href="http://transparente.gt">transparente.gt</a>',
])
?>
<p>
    El proyecto <a href="/">transparente.gt</a> busca recopilar los datos que por ley ya son públicos, y
    convertir esos datos translúcidos en datos realmente transparentes, datos que se puedan procesar para servir
    como herramienta para una investigación profunda.
</p>

<dl class="dl-horizontal">
    <dt>Misión</dt>
    <dd>Ser una base de datos realmente transparente, que toda persona y sistema automatizado pueda usar para sus investigaciones.

    <dt>Visión</dt>
    <dd>No necesitar existir.</dd>
</dl>

<p>
    Un gobierno realmente transparente debe de publicar su información de forma que no sea necesario ser
    re-procesada por un sistema como <a href="/">transparente.gt</a>. La visión es que en un futuro, el gobierno
    publique por ley la información ordenada en forma digital, para que el trabajo que los voluntarios que
    creamos <a href="/">transparente.gt</a> hacemos, no sea necesario. Pero mientras ese día llega,
    <a href="/">transparente.gt</a> recopilará los datos para poder ayudar a hacer visibles las anomalías.
</p>
<p>
    Todo el código usado para la recopilación de los datos, el portal para re-publicar los datos al público, los
    reportes de inconsistencias e incluso la misma base de datos <a href="https://github.com/str/gtt/" target="_blank">
    son de dominio público</a>, haciendo que cualquier persona pueda ver cómo se obtuvieron los datos o pueda colaborar
    o continuar con el proyecto.
</p>