<?
$this->layout()->setVariables([
    'title'    => 'dbCompras',
    'subtitle' => 'proyecto de <a href="http://transparente.gt">transparente.gt</a>',
])
?>
<h2>Antecedente</h2>

<p>
    Cuando el gobierno necesita comprar cualquier cosa, ya sea un escritorio, computadoras, medicina o lo que sea debe
    de publicar esa intención de compra en el portal de <a href="http://guatecompras.gt">Guatecompras</a>.
    Ahí se pueden ver las cotizaciones de las empresas que ofrecen cumplir la compra. Esto se hace de esa forma para
    <i>"transparentar"</i> la compra, pues el pago se hace con el dinero de los ciudadanos. Lamentablemente la
    corrupción y las mafias han logrado encontrar la forma de robar evadiendo la ley.
</p>

<p>
    La información está almacenada en <a href="http://guatecompras.gt">Guatecompras</a>, pero es muy
    difícil poder analizarla. No hay forma de descargarla, exportarla a una hoja de cálculos, poder agrupar pagos o
    hacer ningún tipo de investigación profunda. Al hacer una solicitud de esa información, amparándonos en la
    <a href="http://wikiguate.com.gt/wiki/Ley_de_Acceso_a_la_Informaci%C3%B3n_P%C3%BAblica_%28documento%29">
        Ley de Acceso a la Información Pública
    </a>, nuestra solicitud fue rechazada.
</p>
<p>
    Al darnos cuenta que el gobierno no facilitará nunca la forma para demostrar la corrupción, concluimos que la
    única forma de tener esta información era capturando nosotros los datos y organizarlos en una base de datos para poder
    facilitar cualquier tipo de investigación. Un proceso manual era imposible dada la cantidad de datos que existía, y
    se necesitaba un método que pueda estar actualizado con los datos actuales de
    <a href="http://guatecompras.gt">Guatecompras</a>.
</p>

<center>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- horizontal-content -->
    <ins class="adsbygoogle"
         style="display:inline-block;width:728px;height:90px"
         data-ad-client="ca-pub-4234050867741816"
         data-ad-slot="1596749955"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</center>
<h2>¿Qué es dbCompras?</h2>
<p class="lead">
    El proyecto dbCompras es un sistema automatizado que lee el contenido de las páginas en
    <a href="http://guatecompras.gt">Guatecompras</a>, captura los datos <i>translúcidos</i>, los almacena en una base
    de datos de una forma ordenada y publica esa base de datos como datos transparentes.
</p>

<p>
    Un gobierno realmente transparente debe de publicar su información de forma que no sea necesario ser
    re-procesada por un sistema como dbCompras. La visión es que en un futuro, el gobierno
    publique por ley la información ordenada en forma digital, para que el trabajo que los voluntarios que
    creamos <a href="/">transparente.gt</a> hacemos, no sea necesario. Pero mientras ese día llega,
    dbCompras recopilará los datos para poder ayudar a hacer visibles las anomalías.
</p>
<p>
    Todo el código usado para la recopilación de los datos, el portal para re-publicar los datos al público, los
    reportes de inconsistencias e incluso la misma base de datos <a href="https://github.com/transparentegt/portal" target="_blank">
    son de dominio público</a>, haciendo que cualquier persona pueda ver cómo se obtuvieron los datos o pueda colaborar
    o continuar con el proyecto.
</p>

<h2>Hackatón Desarrollando América Latina 2014</h2>
<p>
    Gracias al proyecto, participamos en diferentes hackatones en el 2014, empapándonos más del tema. Esta fue la
    última presentación pública que dimos del proyecto.
</p>
<div class="row">
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Video</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <iframe width="400" height="360" src="https://www.youtube.com/embed/DRb6v60psXI?rel=0" frameborder="0" allowfullscreen></iframe>
            </div><!-- /.box-body -->

        </div>
    </div>
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Presentación</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <iframe src="//www.slideshare.net/slideshow/embed_code/key/EBiE7mWsGFZEZj" width="425" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe>
            </div><!-- /.box-body -->
        </div>
    </div>
</div>


<h2>Estatus actual</h2>

<p>
    ¡El proyecto fue todo un éxito! Logramos publicar la <strong> primera fuente de
    <a href="http://es.wikipedia.org/wiki/Datos_abiertos">datos abiertos</a></strong> para Guatemala,
    recopilando los datos que por ley ya son públicos, y convertir esos datos  en datos realmente
    transparentes, datos que se puedan procesar para servir como herramienta para una investigación profunda.
</p>
<p>
    De este proyecto logramos obtener 4 resultados tangibles:
</p>

<div class="row">

    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Base de datos descargable</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <p>
                    Los datos están almacenados en una base de datos que puede ser descargada para hacer investigaciones
                    más profundas.
                </p>
                <a class="btn btn-primary" href="/Transparente/db-latest.sql.bz2">descarga la base de datos</a>
            </div><!-- /.box-body -->
        </div>
    </div>    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Datos abiertos</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <p>
                    Los datos obtenidos gracias al sistema automatizado  de dbCompras están publicados en el portal
                    como datos abiertos para ser consultados por cualquier ciudadano.
                </p>
                <a class="btn btn-primary" href="/about/opengov">leer más sobre datos abiertos</a>

            </div><!-- /.box-body -->
        </div>
    </div>    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">API como servicio abierto</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <p>
                    Un API es método de comunicación entre sistemas que permite exportar los datos obtenidos y ser
                    exportados a otro sistema. De esta forma facilitamos que cualquier sistema pueda consumir los datos
                    obtenidos por el proyecto dbCompras.
                </p>
                <a class="btn btn-primary" href="/apigility/documentation/Api-v1">ver API</a>
            </div><!-- /.box-body -->
        </div>
    </div>
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">El sistema automatizado de dbCompras</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <p>
                    El sistema automatizado desarrollado para obtener todos los datos fue desarrollado como software
                    libre, liberando el código y permitiendo que cualquiera que tenga conocimiento de sistemas pueda
                    hacer auditoría del mismo, modificarlo o mejorarlo.
                </p>
                <a class="btn btn-primary" href="https://github.com/transparentegt/portal">descargar código</a>
            </div><!-- /.box-body -->

        </div>
    </div>
</div>

<center>
    <a href="/about/collab" class="btn btn-lg btn-warning">¿Quieres colaborar? Hay muchas formas de hacer un cambio. entérate aquí.</a>
</center>