<?
$this->layout()->setVariables([
    'title'    => '¿Qué es gobierno abierto?',
    'subtitle' => '#openGovernment #openGov',
])
?>

<p class="lead">
    Un gobierno abierto es un gobierno que abre su forma de trabajar para que los ciudadanos tengan confianza en sus
    gobernantes.
</p>
<p>
    La forma hermética, burocrática y oscura en que trabaja el gobierno causa que los ciudadanos desconfíen de sus
    gobernantes. Sus métodos de trabajo generan un ambiente ideal para la corrupción. Al ser los gobernantes, la ley,
    impiden publicar cualquier información que revele la realidad. El ciudadano está totalmente indefenso contra un
    gobierno corrupto.
</p>
<p>
    Cuando un gobierno se abre, vuelve <strong>transparentes</strong> sus procesos para que el ciudadano entienda qué
    está pasando, busca la <strong>colaboración</strong> de los ciudadanos dándoles voto en las decisiones e
    incentivando la <strong>participación</strong>.
</p>
<p>
    En <a href="http://transparente.gt">transparente.gt</a> creemos que para que un gobierno genere confianza debe de cumplir
    con los siguientes principios:
</p>
<ul>
    <li>Utilizar la tecnología para proporcionar servicios a los ciudadanos, haciéndolo un <a href="http://es.wikipedia.org/wiki/Gobierno_electr%C3%B3nico">gobierno electrónico</a>.</li>
    <li>Los datos que publique deben de ser <a href="http://es.wikipedia.org/wiki/Datos_abiertos">datos abiertos</a>.</li>
    <li>El código fuente de los sistemas que generan los datos y servicios, debe de ser <a href="http://es.wikipedia.org/wiki/C%C3%B3digo_abierto">código abierto</a>.</li>
</ul>
<p>
    Si no se cumplen los 3 principios, si se cumplen parcialmente, o si se aplican mal, no se le puede llamar gobierno abierto.
</p>

<center>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- horizontal-content -->
    <ins class="adsbygoogle"
         style="display:inline-block;width:728px;height:90px"
         data-ad-client="ca-pub-4234050867741816"
         data-ad-slot="1596749955"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</center>
<h2>Gobierno electrónico</h2>
<p class="lead">
    Un gobierno que usa tecnología para entregar servicios al ciudadano es un gobierno electrónico.
</p>
<p>
    Somos más de 15 millones de habitantes en Guatemala, y atender las necesidades de todos de una forma eficiente
    requiere de muchos recursos, algo muy costoso, tardado y tedioso. La tecnología es una herramienta que ha demostrado
    ayudar a reducir la necesidad de recursos, reducir costos, acelerar y agilizar procesos, por lo que su adopción en
    los servicios del gobierno es una necesidad primordial.
</p>
<p>
    <a href="http://transparencia.gob.gt/"><abbr title="Comisión Presidencial de Transparencia">COPRET</abbr></a>
    ha ayudado en gran forma creando un portal con el <a href="http://www.transparencia.gob.gt/catalogo-servicios">catálogo de servicios electrónicos</a>
    que el gobierno de Guatemala ha puesto a disposición de sus ciudadanos. Felicitamos su gran esfuerzo y dedicación
    por este gran logro.
</p>
<p>
    Falta mucho por afinar para que estos servicios se encuentren en una forma amigable para que el usuario lo entienda,
    y mucho más para que los consideremos una herramienta de gobierno abierto, pero sabemos que toda adopción es un
    proceso evolutivo.
</p>


<h2>Datos abiertos</h2>
<p class="lead">
    Los datos abiertos son la información que generan las instituciones públicas, publicada en Internet de manera
    estructurada, que permite a cualquier ciudadano su comprensión y manipulación para un análisis profundo de su
    significado.
</p>
<p>
    En Guatemala existe una
    <a  href="http://wikiguate.com.gt/wiki/Ley_de_Acceso_a_la_Informaci%C3%B3n_P%C3%BAblica_%28documento%29">
        Ley de Acceso a la Información Pública
    </a>
    que permite que cualquier ciudadano tenga acceso a toda información de la administración pública. A finales del año
    2,012 según el
    <a href="http://www.transparencia.gob.gt/web/images/Acuerdo/acuerdo_360-2012_COPRET.pdf">acuerdo gubernativo #360-2012</a>
    se crea <a href="http://transparencia.gob.gt/"><abbr title="Comisión Presidencial de Transparencia">COPRET</abbr></a>,
    quién vela por que cada entidad del gobierno cumpla esta ley y publique su información con el fin de mejorar la
    transparencia.
</p>
<p>
    Lamentablemente esta información no es transparente, no es confiable. La información que nos proveen está filtrada,
    procesada y lo peor de todo, la entregan impresa en papel. Con esa información, no se pueden corroborar los datos,
    no se puede verificar la fuente, no se puede agrupar, sumar, ni filtrar, ni hacer cruce de datos ni procesar más
    datos que lo que ya está escrito en papel. A los ciudadanos no nos queda más confiar en el gobierno.
</p>
<blockquote>
    <q>No poder distinguir la verdad que hay detrás, no es transparencia, es translucidez.</q>
    <footer>Stuardo Rodríguez, director de desarrollo <a href="http://transparente.gt">transparente.gt</a></footer>
</blockquote>
<p>
    Un gobierno abierto publica los datos en un formato que los ciudadanos puedan utilizar. Poder hacer análisis
    financieros del gasto público, graficar las empresas mineras en un mapa de calor por cantidad de producto exportado
    o rectificar el conteo de votos de las elecciones presidenciales, son tareas que únicamente se pueden realizar con
    datos abiertos.
</p>

<h2>Código abierto</h2>
<p class="lead">
    Un sistema de computación que permite a toda persona poder ver cómo fue creado, y modificarlo para mejorarlo, es un
    sistema de código abierto.
</p>
<p>
    Recordemos que un gobierno que cambia a un modelo de gobierno abierto, lo hace para generar confianza por medio de
    la <strong>transparencia</strong>. Un sistema o servicio electrónico que no permita
    al ciudadano verificar que los datos publicados no estén alterados, no es un sistema transparente. Un sistema de
    código cerrado es como esas máquinas de apuestas en los casinos, las cuales no permiten saber al usuario si por
    dentro están alteradas para que la casa nunca pierda.
<p>
<p>
    Un sistema abierto permitiría la <strong>colaboración</strong> del desarrollo del mismo por parte de los ciudadanos
    que dominan el tema del desarrollo de sistemas. Un sistema con colaboradores no cambia con el cambio de gobierno,
    lo que es una ventaja para la continuidad de proyectos ya implementados.
</p>
<p>
    Incluso la dirección del desarrollo del sistema y la selección de funcionalidades puede ser seleccionada por los
    ciudadanos interesados, tengan conocimiento o no sobre la creación de sistemas, alentando la <strong>participación</strong>.
</p>
<p class="lead">
    Los proyectos desarrollados por <a href="http://transparente.gt">transparente.gt</a> cumplen los 3 requisitos que
    creemos necesarios para ganarse la confianza de los usuarios de sus sistemas.
</p>
<center>
    <a href="/contact" class="btn btn-lg btn-warning">¿Quieres ponerte en contacto con nosotros? Click aquí para contactarnos.</a>
</center>