<?
$this->layout()->setVariables([
    'title'    => 'reCuento',
    'subtitle' => 'proyecto de <a href="http://transparente.gt">transparente.gt</a>',
])
?>
<h2>Antecedente</h2>

<p>
    2,015 es año electoral en Guatemala. Muchas <a href="https://groups.google.com/forum/#!forum/innovacioncivica">
    iniciativas cívicas</a> estamos interesadas en crear herramientas tecnológicas para empoderar al ciudadano. Muchos
    están interesados en desarrollar aplicaciones para publicar contenidos, informar o recopilar información.
</p>

<center>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- horizontal-content -->
    <ins class="adsbygoogle"
         style="display:inline-block;width:728px;height:90px"
         data-ad-client="ca-pub-4234050867741816"
         data-ad-slot="1596749955"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</center>
<section class="row">
    <div class="col-md-12">
        <h2>¿Qué es reCuento?</h2>
        <p class="lead">
            <img src="/Transparente/img/reCuentoActa.jpg" class="pull-right" />
            El proyecto reCuento consiste en desarrollar un sistema automatizado que lea todas las actas con la suma de
            votos por mesa para confirmar que la suma realizada por el sistema automatizado, sea la misma que el conteo
            oficial.
        </p>
        <p>
            Para probar la viabilidad del proyecto, hemos conseguido las actas de las <span class="badge">16,668</span>
            mesas electorales de las votaciones del año 2,011. Cada mesa emite 3 actas, y al ser 14 valores por acta,
            nos da un total de <span class="badge">700,056</span> valores por validar. Esos son
            <span class="badge" style="background-color: darkred;">700,056</span> posibles errores de digitación, o una
            gran posibilidad de tener un presidente no electo por los ciudadanos.
        </p>
        <p>
            El proyecto ya ha sido implementado en <a href="http://contemosnosotros.org/">El Salvador</a> y en
            <a href="http://conteo.votosocial.org/">Honduras</a>. Utilizando la misma idea que el proyecto
            <a href="http://www.google.com/recaptcha">reCaptcha</a> de mostrar solo una parte de la imagen, sin poder
            asociar el monto con el partido, y con la ayuda de los ciudadanos, se logró verificar el conteo oficial de
            las últimas votaciones en ambos países. Solo con la ayuda de la tecnología y herramientas automatizadas se
            podría hacer un recuento de votos de esta magnitud.
        </p>
        <p>
            Para explicar mejor todo el ciclo del flujo de las actas emitidas por mesa, hemos desarrollado la siguiente
            presentación con un video que explica todo el proceso, y la idea del proyecto.
        </p>
    </div>
</section>

    <br />
<div class="row">
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Video</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <iframe width="400" height="360" src="https://www.youtube.com/embed/JhGB6X_kubs?rel=0" frameborder="0" allowfullscreen></iframe>
            </div><!-- /.box-body -->

        </div>
    </div>
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Presentación</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <iframe src="//www.slideshare.net/slideshow/embed_code/key/2F0NInXJUT5zM"  width="425" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe>
            </div><!-- /.box-body -->
        </div>
    </div>
</div>


<h2>Estatus actual</h2>

<p>
    Se lograron obtener las actas de las votaciones del 2,011, actas que el Tribunal Supremo Electoral ya ha retirado
    de su sitio en Internet. Se ha desarrollado un sistema para cortar y generar las imáges individuales que se mostrarían
    a los ciudadanos para digitar.
</p>
<p>
    Actualmente estamos en el análisis de la viabilidad del proyecto dadas las muchas incosistencias de los documentos
    escaneados por el Tribunal Supremo Electoral.
</p>

<center>
    <a href="/about/collab" class="btn btn-lg btn-warning">¿Quieres colaborar? Hay muchas formas de hacer un cambio. entérate aquí.</a>
</center>