<?php
/**
 * Menú lateral
 *
 * @todo Marcar como activo el menú padre
 */
?>
<ul class="sidebar-menu">
<?php foreach ($this->container as $page) : ?>
    <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
    <?php // when using partials we need to manually check for ACL conditions ?>
    <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) { continue; } ?>
    <?php $hasChildren = $page->hasPages(); ?>
    <?php if (!$hasChildren) : ?>
         <li <?php if($page->isActive()) echo 'class="active"'?>>
            <a href="<?php echo $page->getHref() ?>">
                <?php echo $this->translate($page->getLabel()) ?>
            </a>
        </li>
    <?php else : ?>
    <li class="treeview">
        <a href="#"><?php echo $this->translate($page->getLabel()) ?><i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
            <?php foreach ($page->getPages() as $child) : ?>
                <?php // when using partials we need to manually check for ACL conditions ?>
                <?php if(!$child->isVisible() || !$this->navigation()->accept($child)) { continue; } ?>
                <li <?php if($child->isActive()) echo 'class="active"'?>>
                    <a href="<?php echo $child->getHref() ?>">
                        <?php echo $this->translate($child->getLabel()) ?>
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    </li>
    <?php endif ?>
<?php endforeach ?>
</ul>
