<?php
/**
 * Menú lateral
 *
 * @todo Marcar como activo el menú padre
 */
?>
<ul class="nav sidebar-menu">
    <li class="header">menu</li>
<?php foreach ($this->container as $page) : ?>
    <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
    <?php // when using partials we need to manually check for ACL conditions ?>
    <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) { continue; } ?>
    <?php $hasChildren = $page->hasPages(); ?>
    <?php if (!$hasChildren) : ?>
         <li <?php if($page->isActive()) echo 'class="active"'?>>
            <a href="<?php echo $page->getHref() ?>">
                <?php echo $this->translate($page->getLabel()) ?>
            </a>
        </li>
    <?php else : ?>
    <li class="treeview">
        <a href="#"><?php echo $this->translate($page->getLabel()) ?><i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
            <?php foreach ($page->getPages() as $child) : ?>
                <?php // when using partials we need to manually check for ACL conditions ?>
                <?php if(!$child->isVisible() || !$this->navigation()->accept($child)) { continue; } ?>
                <li <?php if($child->isActive()) echo 'class="active"'?>>
                    <a href="<?php echo $child->getHref() ?>">
                        <?php echo $this->translate($child->getLabel()) ?>
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    </li>
    <?php endif ?>
<?php endforeach ?>
</ul>
<hr />
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- responsive-menu -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-4234050867741816"
     data-ad-slot="8131294755"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
