<hr />
<p>
    <strong>Nota:</strong> Todos los datos publicados por <a href="/">transparente.gt</a> son información
    pública, recolectada de portales públicos de <em>"transparencia"</em>. <a href="/">transparente.gt</a> solo
    publica los datos recolectados, toda interpretación de los datos es responsabilidad de quién los interprete
    y no nos hacemos responsables del uso que se le den.
</p>