<?php
/**
 * Elemento reutilizable para paginación de datos
 *
 * @todo Agregar links para primera y última página (issue #24)
 */

/* @var $this \Zend\View\Renderer\PhpRenderer */
?>
<?php if ($this->pageCount): ?>
     <ul class="pagination">
         <!-- Previous page link -->
         <?php if (isset($this->previous)): ?>
             <li><a href="<?=$this->url($this->route, $this->routeParams)?>?page=<?=$this->previous; ?>"> « </a></li>
         <?php else: ?>
             <li class="disabled"><a href="#"> « </a></li>
         <?php endif; ?>

         <!-- Numbered page links -->
         <?php foreach ($this->pagesInRange as $page): ?>
             <?php if ($page != $this->current): ?>
                 <li><a href="<?=$this->url($this->route, $this->routeParams)?>?page=<?=$page?>"><?=$page?></a></li>
             <?php else: ?>
                 <li class="active"><a href="#"><?php echo $page; ?></a></li>
             <?php endif; ?>
         <?php endforeach; ?>

         <!-- Next page link -->
         <?php if (isset($this->next)): ?>
             <li><a href="<?=$this->url($this->route, $this->routeParams)?>?page=<?=$this->next?>"> » </a> </li>
         <?php else: ?>
             <li class="disabled"><a href="#"> » </a></li>
         <?php endif; ?>
     </ul>
 <?php endif; ?>
 <p class="small" style="margin-top: -20px;">
     Mostrando <?=number_format($this->itemCountPerPage)?> de un total de <?=number_format($this->totalItemCount)?> registros.
 </p>