<?php
 // module/Album/view/album/album/add.phtml:


 $title = 'Agregar Municipio';
 $this->headTitle($title);
 ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="/transparente/geoMunicipios">
		<span>Regresar</span>
	</a>
</p>
 <?php
 $form->setAttribute('action', '/transparente/geoMunicipios/add');
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formCollection($form);
 echo $this->form()->closeTag();
 ?>