<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Editar Municipio';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="/transparente/geoMunicipios">
		<span">Regresar</span>
	</a>
</p>
<?php
$form = $this->form;
$form->setAttribute('action', '/transparente/geoMunicipios/edit/'.$this->id);
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

?>