<?php

 $title = 'Municipios';
 $this->headTitle($title);
 ?>
<h1 class="tituloSeccion"><?php echo $this->escapeHtml($title); ?></h1>
<p class="menuSeccion">
     <a class="button" href="/transparente/geoMunicipios/add" >
		<span>Agregar Municipio</span>
	</a>
</p>
<table class="table">
<tr>
    <th>ID</th>
    <th>Nombre</th>
    <th>Departamento</th>
    <th>&nbsp;</th>
</tr>
 <?php foreach ($this->paginator as $item) : ?>
 <tr>
 	<td><?php $item->id;?></td>
    <td><?php echo $this->escapeHtml($item->nombre);?> 	
	<td><?php echo $this->escapeHtml(getDepartamento($this->db, $item->id_geo_departamento)); ?></td>
    <td>
        <a href="/transparente/geoMunicipios/edit/<?php echo $item->id;?>">Editar</a>
        <a href="/transparente/geoMunicipios/delete/<?php echo $item->id;?>">Borrar</a>
    </td> 
 </tr>
 <?php endforeach; ?>
 </table>
  <?php
 // add at the end of the file after the table
 echo $this->paginationControl(
     // the paginator object;
     $this->paginator,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     array('partial/paginator.phtml', 'geoMunicipios'),
     // the route to link to when a user clicks a control link
     array(
         'route' => 'transparente'
     )
 );
 
 function getDepartamento($db, $depto)
 {
 	$departamento = $db->query('select nombre from geo_departamentos where id='.$depto)->execute()->current();
	return $departamento['nombre'];
 }
 ?>