<?php
/* @var $this Zend\View\Renderer\PhpRenderer */
?>
<h1>Sobre el proyecto</h1>

<h2>Antecedente</h2>

<p>
Guatemala ocupa el <a href="http://www.transparency.org/cpi2013/results" target="_blank">puesto 123 de los países más corrupstos</a> en el informe 2013 publicado por <a href="http://www.transparency.org/" target="_blank">Transparencia Internacional</a>. Los que vivimos en este país lo sentimos peor, al punto que los ciudadanos no confían en el gobierno y se organizan diferentes grupos civiles con el fin de detener tanto abuso de poder.
</p><p>
En el año 2008 se publica <a href="http://wikiguate.com.gt/wiki/Ley_de_Acceso_a_la_Informaci%C3%B3n_P%C3%BAblica_%28documento%29" target="_blank">Ley de Acceso a la Información Pública</a> que permite el acceso a toda información de la administración pública. A finales del año 2012 se crea <abbr title="Comisión Presidencial de Transparencia">COPRET</abbr>, quién vela por que cada entidad del gobierno publique sus información con el fin de mejorar la transparencia, según el <href="http://www.transparencia.gob.gt/web/images/Acuerdo/acuerdo_360-2012_COPRET.pdf" target="_blank">Acuerdo Gubernativo No. 360-2012</a>. Y hay una oficina <sup>(se requiere más información)</sup> donde se puede hacer solicitudes puntuales de esta información.

</p><p>
Lamentablemente esta información no es transparente. La información que nos proveen está filtrada, procesada y lo peor de todo, la entregan impresa en papel. Con esa información, no se puede corroborar los datos, no se puede verificar la fuente, no se puede agrupar, sumar, ni filtrar, ni hacer cruce de datos ni procesar más datos que lo que ya está escrito en papel. Lo que permite ver a través de ello pero que todavía opaca al punto de no permitir ver realmente que hay detrás, no es transparencia, es algo translúcido.

</p><p>
Aún con la Ley De Acceso a la Información, a los ciudadanos no nos queda más que seguir mintiéndonos a nosotros mismos para creernos que el gobierno está haciendo bien su trabajo.
</p>
<h2>¿Qué es Guatemala Transparente?</h2>
    <img alt="Guatemala Transparente" title="Guatemala Transparente" class="pull-right"
    src="<?=$this->basePath()?>/Transparente/img/logo-home.png" />
<p>
El proyecto <abbr title="Guatemala Transparente">GTT</abbr> busca recopilar los datos que por ley ya son públicos, y convertir esos datos translúcidos en datos realmente transparentes, datos que se puedan procesar para servir como herramienta para una investigación profunda.
</p>
    <dl>
        <dt>Misión</dt>
        <dd>Ser una base de datos realmente transparente, que toda persona y sistema automatizado pueda usar para sus investigaciones.

        <dt>Visión</dt>
        <dd>No necesitar existir.</dd>
    </dl>

<p>
Un gobierno realmente transparente debe de publicar su información de forma que no sea necesario ser re-procesada por un sistema como GTT. La visión es que en un futuro, el gobierno publique por ley la información ordenada en forma digital, para que el trabajo que los voluntarios que creamos GTT hacemos, no sea necesario. Pero mientras ese día llega, GTT recopilará los datos para poder ayudar a hacer visibles las anomalías.
</p>
<p>
    Todo el código usado para la recopilación de los datos, el portal para re-publicar los datos al público, los
    reportes de inconsistencias e incluso la misma base de datos <a href="https://github.com/str/gtt/" target="_blank">
    son de dominio público</a>, haciendo que cualquier persona pueda ver cómo se obtuvieron los datos o pueda colaborar
    o continuar con el proyecto.
</p>

<h2>¿Quiénes hacen GTT?</h2>
<p>
    El proyecto es un trabajo creado por puro voluntariado, invirtiendo sus horas libres en la escritura del sistema,
    reuniones para pedir información, digitando el texto publicado en papel y solucionando todo bloqueo que un sistema
    corrupto pone como obstáculo para no poder indentificar la corrupción.
</p><p>

No hay ninguna ONG, ningún partido político, ningúna organización; somos simples ciudadanos cansados de ver políticos enriquecerse mientras dicen que no hay dinero para escuelas u hospitales; cansados de ver mansiones aparecer de la nada mientras no hay dinero para infraestructura; cansados de ver nuevos impuestos cuando no tenemos con que pagar el pan de cada día.
</p><p>

¿Quienes somos los que hacemos GTT? Somos las víctimas de una dictadura montada sobre un monstruo de corrupción. Somos el David contra Goliat, y esta es nuestra honda y piedra.
</p>
<h2>¿Cómo nace GTT?</h2>

<a href="https://www.facebook.com/groups/hhguatemala/" target="_blank">
    <img src="http://larutadeldinero.info/imagenes/hh.png" alt="hacks/hackers" class="pull-right"/>
</a>
<p>
    <a href="http://hackshackers.com">Hacks/Hackers</a> es un movimiento <a href="http://hackshackers.com/chapters/">internacional</a>
    que reune periodistas con gente de tecnología, y entre ambos poder crear noticias con fundamentos técnicos sólidos.
    Hacks/Hackers <strong>no</strong> se refiere al término mal-asociado a vándalos informáticos, sino a la
    <a href="http://es.wikipedia.org/wiki/Cultura_hacker">cultura de aficionados a la informática</a>.
</p>
<p>
    En un evento organizado por <a href="https://www.facebook.com/groups/hhguatemala/" target="_blank">Hacks/Hackers
    Guatemala</a> enfocado en cómo reconocer el flujo del gasto público, identificamos que no podemos intentar detectar
    ningún flujo de nada pues no hay datos públicos transparentes útiles para el ejercicio. Desde ese día, algunos
    participantes del evento iniciaron el proyecto. Sabemos que nos falta mucho por hacer pero si no somos nosotros,
    el gobierno no lo hará por nosotros.
</p
><p>
    El cambio debe de venir de la iniciativa civil; solo los ciudadanos podemos exponer las irregularidades que el
    gobierno no quiere hacer públicas. Somos el cambio que queremos ver en nuestro país.
</p>

<h2>¿Cómo puedo participar?</h2>
<p>
    ¿Estás interesado en apoyar? Los aportes que podemos recibir son:
</p>
<ul>
    <li>Apoyo técnico: todo el código del proyecto es público y se puede ver, editar y mejorar en el portal de
    github en <a href="https://github.com/str/gtt/" target="_blank">guatemala transparente</a></li>

    <li>Tareas específicas: los pendientes por hacer son varios, en especial a estas alturas del proyecto. Llevamos
    un manejador de incidencias de estas tareas específicas, las cuales se pueden ver en el
    <a href="https://github.com/str/gtt/issues?state=open" target="_blank">manejador de incidencias</a></li>

    <li>Donaciones económicas: a pesar que el proyecto está creado por voluntariado que aporta su tiempo libre para la
    investigación y creación de este, se tienen gastos para contratar el servicio de alojamiento, compra del dominio y
    demás que están pendientes. Cualquier donación es bienvenida.
        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="48SXBFDP69SP2">
            <input type="image" src="https://www.paypalobjects.com/es_ES/ES/i/btn/btn_donateCC_LG.gif" name="submit" alt="PayPal. La forma rápida y segura de pagar en Internet.">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
        </form>
    </li>
</ul>

<hr />
<p>
    <strong>Nota:</strong> Todos los datos publicados por GTT son información pública, recolectada de portales públicos de <em>"transparencia"</em>. GTT solo publica los datos recolectados, toda interpretación de los datos es responsabilidad de quién los interprete y no nos hacemos responsables del uso que se le den.
</p>
