<?php
/* @var $this Zend\View\Renderer\PhpRenderer */
?>
<h1>Sobre el proyecto</h1>
<p>
    <img alt="Guatemala Transparente" title="Guatemala Transparente" class="pull-right"
    src="<?=$this->basePath()?>/Transparente/img/logo-home.png" />

    <a href="http://gtt.maphpia.com">Guatemala Transparente</a> es un proyecto organizado por voluntariado, buscando
    demostrar anomalías del gobierno recopilando datos de los diferentes portales para hacer análisis de los datos y
    creando consultas automatizadas para detectar posibles problemas.
</p>
<p>
    Todo el código usado para la recopilación de los datos, el sistema para hacerlos públicos e incluso los datos
    recopilados son de dominio público, haciendo que cualquier persona pueda ver cómo se obtuvieron los datos o pueda
    colaborar o continuar con el proyecto.
</p>
<p>
    El proyecto es creado y mantenido como aporte a la sociedad guatemalteca, buscando crear ese mejor futuro que todos
    queremos, que no podemos esperar que el gobierno nos lo de. El cambio debe de venir de adentro, solo los ciudadanos
    podemos exponer las irregularidades que el gobierno no quiere hacer públicas. Somos el cambio que queremos ver en
    nuestro país.
</p>
<p>
    ¿Estás interesado en apoyar? Los aportes que podemos recibir son:
</p>
<ul>
    <li>Apoyo técnico: todo el código del proyecto es público y se puede ver, editar y mejorar en el protal en
    github en <a href="https://github.com/str/gtt/" target="_blank">guatemala transparente</a></li>

    <li>Tareas específicas: los pendientes por hacer son varios, en especial a estas alturas del proyecto. Llevamos
    un manejador de incidencias de estas tareas específicas, las cuales se pueden ver en el
    <a href="https://github.com/str/gtt/issues?state=open" target="_blank">manejador de incidencias</a></li>

    <li>Donaciones económicas: a pesar que el proyecto está creado por voluntariado que aporta su tiempo libre para la
    investigación y creación de este, se tienen gastos para contratar el servicio de alojamiento, combra del dominio y
    demás que están pendientes. Cualquier donación es bienvenida.
        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="48SXBFDP69SP2">
            <input type="image" src="https://www.paypalobjects.com/es_ES/ES/i/btn/btn_donateCC_LG.gif" name="submit" alt="PayPal. La forma rápida y segura de pagar en Internet.">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
        </form>
    </li>
</ul>