<h1>Contacto</h1>

<p>Estamos interesados en saber sus opiniones o comentarios.</p>

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Formulario de contacto</h3>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form role="form" method="post">
        <div class="box-body">

            <div class="form-group">
                <label for="contact[name]">Su nombre:</label>
                <input class="form-control" id="contact[name]" name="contact[name]" placeholder="nombre completo" />
            </div>
            <div class="form-group">
                <label for="contact[email]">Dirección de correo electrónico:</label>
                <input type="email" class="form-control" id="contact[email]" name="contact[email]" id="contact[email]" placeholder="ciudadano@ejemplar.com" />
            </div>
            <div class="form-group">
                <label for="contact[comments]">Comentarios:</label>
                <textarea placeholder="Comentarios..." rows="3" class="form-control" name="contact[comments]" id="contact[comments]"></textarea>
            </div>
            <div class="g-recaptcha" data-sitekey="6Lf_lwcTAAAAAKk7yb5eAdy8ELDlchvpO_a7Cvxu"></div>
        </div><!-- /.box-body -->
        <div class="box-footer">
            <button class="btn btn-primary" type="submit">enviar</button>
        </div>
    </form>
</div>
<script src='https://www.google.com/recaptcha/api.js'></script>