<?php
/* @var $this Zend\View\Renderer\PhpRenderer */
?>
<style>
.jumbotron    {margin-top: 1em;}
.jumbotron h1 {font-size: 40px; margin-top: -10px;}
.jumbotron p  {font-size: 14px;}
</style>
<div class="jumbotron">
    <div class="row text-center">
        <img itemprop="image" alt="transparente.gt" title="transparente.gt" src="<?=$this->basePath()?>/Transparente/img/logo-home.png">
    </div>
    <p>
        El proyecto <a href="/">transparente.gt</a> busca ser la primera <strong> fuente de
        <a href="http://es.wikipedia.org/wiki/Datos_abiertos">datos abiertos</a></strong> para Guatemala, recopilando
        los datos que por ley ya son públicos, y convertir esos datos <i>translúcidos</i> en datos realmente
        transparentes, datos que se puedan procesar para servir como herramienta para una investigación profunda.
    </p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Resumen de datos recopilados</h3>
            </div>
            <div class="panel-body">
                <p>Estos son los datos recopilados hasta el momento:</p>
                <ul>
                    <? foreach ($this->totals as $count) :?>
                    <li><span class="badge"><?=number_format($count['total'])?></span> <?=$count['entidad']?></li>
                    <? endforeach ?>
                    <li><span class="badge">4</span> reportes de inconsistencias</li>
                </ul>
                <p>
                    Descarga la base de datos en formato <a href="http://www.mysql.com/">Oracle's MySQL</a>.
                </p>

                <a class="btn btn-success pull-right" href="<?=$this->basepath()?>/Transparente/db-latest.sql.bz2">
                    Descarga la base de datos »
                </a>
            </div>
        </div>
    </div>


    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">¿Cómo colaborar?</h3>
            </div>
            <div class="panel-body">
                <p>
                    "Apenas llevamos 3 trazos de un plano de 3 millones de lineas" y hay mucho que hacer. Las tareas
                    específicas que hemos encontrado las hemos publicado en el
                    <a href="https://github.com/str/gtt/issues?state=open" target="_blank">
                        manejador de incidencias
                    </a>
                    donde publicamos las tareas donde podríamos recibir ayuda.
                </p>
                <p>
                    ¿Encontraste un problema y quieres reportarlo? También podés publicar la incidencia para que lo
                    arreglemos.
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="https://github.com/str/gtt/issues?state=open" target="_blank">
                        Ver manejador de incidencias »
                    </a>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Software Libre</h3>
            </div>
            <div class="panel-body">
                <p>
                    <a href="/">transparente.gt</a> es un proyecto colaborativo donde, con el tema de transparencia siempre
                    primero, el código fuente es libre para que cualquiera lo pueda ver, mejorar, y replicar.
                </p>
                <p>
                    El status del proyecto se puede seguir en la página en github.
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="https://github.com/str/gtt" target="_blank">
                        Ver el proyecto en GitHub »
                    </a>
                </p>
            </div>
        </div>
    </div>


</div>
