<?php
/* @var $this Zend\View\Renderer\PhpRenderer */
?>
<style>
.jumbotron    {margin-top: 1em;}
.jumbotron h1 {font-size: 40px; margin-top: -10px;}
.jumbotron p  {font-size: 14px;}
</style>
<div class="jumbotron">
    <div class="row text-center">
        <img alt="Guatemala Transparente" title="Guatemala Transparente" src="<?=$this->basePath()?>/Transparente/img/logo-home.png">
    </div>
    <p>
        <a href="http://gtt.maphpia.com">Guatemala Transparente</a> busca ser la primera fuente de datos totalmente
        libre para análisis público. La meta es ser una herramienta de ayuda para periodistas e investigadores en la
        tarea de evidenciar prácticas de corrupción entre las municipalidades y las empresas contratadas para proveer
        servicios y productos al gobierno.

    <p>
    </p>
        Hemos empezado con recopilar los datos de los 50 proveedores que más dinero les ha dado el gobierno este año (2014).
        Ya tenemos barridos los datos generales, nombres comerciales y representantes legales y nuestra meta es poder
        tener todo almacenado para intetificar los problemas.
    </p>
    <p class="text-right">
        <a class="btn btn-success btn-lg" href="<?=$this->basepath()?>/transparente/proveedores">
            Ver los resultados »
        </a>
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">¿Cómo colaborar?</h3>
            </div>
            <div class="panel-body">
                <p>
                    "Apenas llevamos 3 trazos de un plano de 3 millones de lineas" y hay mucho que hacer. Las tareas
                    específicas que hemos encontrado las hemos publicado en el
                    <a href="https://github.com/str/guatecompras-transparente/issues?state=open" target="_blank">
                        manejador de incidencias
                    </a>
                    donde publicamos las tareas donde podríamos recibir ayuda.
                </p>
                <p>
                    ¿Encontraste un problema y quieres reportarlo? También podés publicar la incidencia para que lo
                    arreglemos.
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="https://github.com/str/guatecompras-transparente/issues?state=open" target="_blank">
                        Ver manejador de incidencias »
                    </a>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Software Libre</h3>
            </div>
            <div class="panel-body">
                <p>
                    Guatecompras Transparente es un proyecto colaborativo donde, con el tema de transparencia siempre
                    primero, el código fuente es libre para que cualquiera lo pueda ver, mejorar, y replicar.
                </p>
                <p>
                    El status del proyecto se puede seguir en la página en github.
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="https://github.com/str/guatecompras-transparente" target="_blank">
                        Ver el proyecto en GitHub »
                    </a>
                </p>
            </div>
        </div>
    </div>


    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Hacks/Hackers</h3>
            </div>
            <div class="panel-body">
                <p>
                    GTCT surgió como la idea más interesante para el evento de
                    <a href="http://larutadeldinero.info/" target="_blank">La Ruta del Dinero</a>, hackatón latinoamericano. Un mes
                    después de esa reunión se saca la primvera versión 0.1-alpha gracias al esfuerzo y sacrificación de
                    horas libres
                </p>
                <p>
                    Para saber más sobre el proyecto del evento pueden ver la página en:
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="http://larutadeldinero.info/" target="_blank">
                        <img src="http://larutadeldinero.info/imagenes/hh.png" alt="hacks/hackers" />
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>