<?php
$title = 'Agregar Domicilio';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->basepath()?>/transparente/domicilios">
        <span>Regresar</span>
    </a>
</p>
 <?php
 $form->setAttribute('action', $this->basepath().'/transparente/domicilios/add');
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formCollection($form);
 echo $this->form()->closeTag();
 ?>