<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Guatecompras Transparente')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/Transparente/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/Transparente/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css')
         ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js')
            ->prependFile('//code.jquery.com/jquery-migrate-1.2.1.min.js')
            ->prependFile('//code.jquery.com/jquery-1.11.0.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <img alt="Guatecompras Transparente" src="<?=$this->basePath()?>/Transparente/img/logo-menu.png" style="height: 34px; margin-top: -12px;" />
                        &nbsp; Guatecompras Transparente
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <style>
                footer > * {float: left; margin-right: 20px; margin-bottom: 10px;}
            </style>
            <hr>
            <footer>
                <a href="http://framework.zend.com" title="Zend Framework Version: <?php echo \Zend\Version\Version::VERSION ?>" >
                    <img src="<?=$this->basePath()?>/img/zf_powered.png" alt="Zend Framework Version: <?php echo \Zend\Version\Version::VERSION ?>" />
                </a>
                <a href="http://maphpia.com" title="Desarrollado por La Maphpia" >
                    <img src="<?=$this->basePath()?>/img/maphpia_powered.png" alt="Desarrollado por La Maphpia" />
                </a>
                <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank"  style="display: inline;">
                    <input type="hidden" name="cmd" value="_s-xclick" />
                    <input type="hidden" name="hosted_button_id" value="48SXBFDP69SP2" />
                    <input type="image" src="https://www.paypalobjects.com/es_ES/ES/i/btn/btn_donate_SM.gif" name="submit" alt="PayPal. La forma rápida y segura de pagar en Internet." />
                    <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1" />
                </form>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
          ga('create', 'UA-52493800-1', 'auto');
          ga('send', 'pageview');
        </script>
    </body>
</html>