<?php
/**
 * Layout para el portal http://transparente.gt basado en AdminLTE
 *
 * @link https://almsaeedstudio.com/
 */
/* @var $this Zend\View\Renderer\PhpRenderer */
echo $this->doctype();
?>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <?php echo $this->headTitle('transparente.gt')->setSeparator(' - ')->setAutoEscape(false) ?>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/Transparente/img/favicon.ico'])
            ->prependStylesheet($this->basePath() . '/Transparente/css/style.css')
            ->prependStylesheet('//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css')
            ->prependStylesheet('/AdminLTE/dist/css/skins/skin-blue-light.min.css')
            ->prependStylesheet('/AdminLTE/dist/css/AdminLTE.min.css')
            ->prependStylesheet('//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css')
            ->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css')
            ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css')
        ?>
        <?php echo $this->headScript()
            ->prependFile('/Transparente/js/transparente.js')
            ->prependFile('/AdminLTE/dist/js/app.min.js')
            ->prependFile('//cdn.rawgit.com/rochal/jQuery-slimScroll/master/jquery.slimscroll.min.js')
            ->prependFile('//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js')
            ->prependFile('//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js')
            ->prependFile('//code.jquery.com/jquery-migrate-1.2.1.min.js')
            ->prependFile('//code.jquery.com/jquery-1.11.3.min.js')
            ->prependFile($this->basePath() . 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . 'https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ?>
        <?php echo $this->inlineScript() ?>
        <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    </head>
    <body class="skin-blue-light fixed">
        <div class="wrapper">
            <!-- Main Header -->
            <header class="main-header">
                <!-- Logo -->
                <a href="/" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini" style="background: white;">
                        <img src="<?=$this->basePath()?>/Transparente/img/logo-menu.png" alt="transparente.gt" style="margin-right: 4px;" />
                    </span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg" style="">
                        <img src="<?=$this->basePath()?>/Transparente/img/logo-menu.png" alt="transparente.gt" style="margin-right: 4px;" />
                        <b>transparente.gt</b>
                    </span>
                </a>

                <!-- Header Navbar -->
                <nav class="navbar navbar-static-top" role="navigation">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <form action="http://www.google.com/cse" id="cse-search-box" class="navbar-form navbar-right" role="search">
                        <!-- <script type="text/javascript" src="http://www.google.com/cse/brand?form=cse-search-box&amp;lang=en"></script>  -->
                        <input name='cx' type='hidden' value='017086301930479271166:9j1mjxfc494'/>
                        <div class="form-group">
                            <input type="text" class="form-control" name="q" placeholder="buscar">
                        </div>
                        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                    </form>
                </nav>
            </header>

            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- Sidebar Menu -->
                    <?=$this->navigation('navigation')->menu()->setPartial(array('partial/menu.phtml', 'default'));?>
                </section>
                <!-- /.sidebar -->
            </aside>

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <!-- Content Header (Page header) -->
                <? if ($this->title) :?>
                    <section class="content-header">
                        <h1>
                            <?php echo $this->title ?>
                            <? if ($this->subtitle) :?>
                                <small><?php echo $this->subtitle ?></small>
                            <? endif ?>
                        </h1>
                        <!--
                        <ol class="breadcrumb">
                            <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                            <li class="active">Here</li>
                        </ol>
                         -->
                    </section>
                <? endif ?>
                <!-- Main content -->
                <section class="content body">
                    <?
                     $flash = $this->flashMessenger();
                     $flash->setMessageOpenFormat('<div%s>
                         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                             &times;
                         </button>
                         <ul><li>')
                         ->setMessageSeparatorString('</li><li>')
                         ->setMessageCloseString('</li></ul></div>');

                     echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
                     echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
                     echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
                     echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
                     ?>
                    <!-- Your Page Content Here -->
                    <?php echo $this->content ?>
                </section><!-- /.content -->
            </div><!-- /.content-wrapper -->

            <!-- Main Footer -->
            <footer class="main-footer">
                <!-- To the right -->
                <div class="pull-right hidden-xs">
                    <a href="http://maphpia.com" title="Desarrollado por La Maphpia" target="_blank">
                        <img src="<?=$this->basePath()?>/img/maphpia_powered.png" alt="Desarrollado por La Maphpia" />
                    </a>
                    <br />
                    <a href="/about/collab" title="cómo colaborar"  style="margin-top: 4px; float: right" >
                        <img src="https://www.paypalobjects.com/es_ES/ES/i/btn/btn_donate_SM.gif" alt="cómo colaborar" />
                    </a>
                </div>
                <!-- Default to the left -->
                <small>
                    © 2014-<?=date('Y')?> <a href="/transparente/index/about">transparente.gt</a> |
                    Datos publicados bajo la
                    <a href="http://opendatacommons.org/licenses/odbl/1.0/">Licencia de Base de Datos Abierta</a>.
                    Cualquier derecho en los contenidos individuales de la base de datos están licenciados bajo la
                    <a href="http://opendatacommons.org/licenses/dbcl/1.0">Licencia de Contenidos de Bases de Datos Abiertos</a>.
                </small>
            </footer>
        </div><!-- ./wrapper -->

        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
          ga('create',  'UA-52493800-1', 'auto');
          ga('require', 'linkid', 'linkid.js');
          ga('require', 'displayfeatures');
          ga('send',    'pageview');
        </script>
        </body>
</html>