<?php
/**
 * Listar los proveedores
 *
 * @todo usar paginador para los proveedores
 * @todo poder reordenar el listado
 */

/* @var $this Zend\View\Renderer\PhpRenderer */

$pager = $this->paginationControl(
        // the paginator object
        $this->paginator,
        // the scrolling style
        'sliding',
        // the partial to use to render the control
        'partial/paginator.phtml',
        // the route to link to when a user clicks a control link
        ['route' => 'transparente/default', 'routeParams' => ['controller' => 'proveedores']]
);
?>
<h1>Proveedores</h1>
<p>
    Catálogo de proveedores importados. Actualmente tenemos los primeros 500 proveedores con los montos más altos
    pagados por el gobierno. Son los datos que usamos para recolectar la información.
</p>
<table class="table">
    <thead>
        <tr>
            <th>nombre</th>
            <th class="text-right">nit</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $entity) : /* @var $entity Transparente\Model\Entity\Proveedor */?>
        <tr>
            <td>
                <a href="<?=$this->basepath()?>/transparente/proveedores/detalles/<?=$entity->getId()?>">
                    <?=$entity->getNombre()?>
                </a>
            </td>
            <td class="text-right"><?=$entity->getNit()?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
<?=$pager?>