<?php
/**
 * Listar los proveedores
 *
 * @todo usar paginador para los proveedores
 * @todo poder reordenar el listado
 */

/* @var $this Zend\View\Renderer\PhpRenderer */
?>
<h1>Proveedores sin domicilio fiscal</h1>
<p>
    Del catálogo de proveedores recopilados, este es el listado de los proveedores que no tienen dirección fiscal
    publicada. Ponemos a la par si detectamos o no la dirección comercial como comparativa.
</p>
<table class="table">
    <thead>
        <tr>
            <th>nombre</th>
            <th class="text-right">nit</th>
            <th>dirección fiscal</th>
            <th>dirección comercial</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->vars('entities') as $entity) : /* @var $entity Transparente\Model\Entity\Proveedor */?>
        <tr>
            <td>
                <a href="<?=$this->basepath()?>/transparente/proveedores/detalles/<?=$entity->getId()?>">
                    <?=$entity->getNombre()?>
                </a>
            </td>
            <td class="text-right"><?=$entity->getNit()?></td>
            <td>
                <a target="_blank" href="<?=$entity->getUrlGuatecompras()?>" >
                    <?=($entity->getDomicilioFiscal()) ? '' : 'no detectada'?>
                    <span class="glyphicon glyphicon-new-window"></span>
                </a>
            </td>
            <td>
                <?=($entity->getDomicilioComercial()) ? 'si tiene' : 'no detectada'?>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>