<?php
/**
 * Listar los proveedores
 *
 * @todo usar paginador para los proveedores
 * @todo poder reordenar el listado
 */

/* @var $this Zend\View\Renderer\PhpRenderer */
/* @var $this->paginator Zend\Paginator\Paginator */


$reportTotal = $this->paginator->getPages()->totalItemCount;
$percent     = floor($reportTotal * 100 / $this->total);
$pager       = $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style
    'sliding',
    // the partial to use to render the control
    'partial/paginator.phtml',
    // the route to link to when a user clicks a control link
    ['route' => 'transparente/default', 'routeParams' => ['controller' => 'proveedores', 'action' => 'no-fiscal']]
);

?>
<h1>Proveedores sin domicilio fiscal</h1>
<p>
    Del catálogo de proveedores recopilados, este es el listado de los proveedores que no tienen dirección fiscal
    publicada. De los  <span class="badge"><?=number_format($this->total)?></span> proveedores en Guatecompras, más del
    <span class="badge"><?=$percent ?>%</span> de proveedores no tienen su dirección fiscal publicada en por el portal de
    Guatecompras.  Ponemos a la par si detectamos o no la dirección comercial como comparativa.
</p>
<center>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- horizontal-content -->
    <ins class="adsbygoogle"
         style="display:inline-block;width:728px;height:90px"
         data-ad-client="ca-pub-4234050867741816"
         data-ad-slot="1596749955"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</center>
<table class="table">
    <thead>
        <tr>
            <th>nombre</th>
            <th class="text-right">nit</th>
            <th>dirección fiscal</th>
            <th>dirección comercial</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->vars('paginator') as $entity) : /* @var $entity Transparente\Model\Entity\Proveedor */?>
        <tr>
            <td>
                <a href="<?=$this->basepath()?>/transparente/proveedores/detalles/<?=$entity->getId()?>">
                    <?=$entity->getNombre()?>
                </a>
            </td>
            <td class="text-right"><?=$entity->getNit()?></td>
            <td>
                <a href="<?=$entity->getUrlGuatecompras()?>" >
                    <?=($entity->getDomicilioFiscal()) ? '' : 'no detectada'?>
                </a>
            </td>
            <td>
                <?=($entity->getDomicilioComercial()) ? 'si tiene' : 'no detectada'?>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
<?=$pager?>
<?=$this->partial('partial/opendatadisclamer') ?>
