<?php
/**
 * Listar los empleados municipales
 */

/* @var $this Zend\View\Renderer\PhpRenderer */
?>
<script type="text/javascript">
$(document).ready(function(){
    $('.data-table').dataTable({
        language: {url: '//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json'},
        processing: true,
        serverSide: true,
        ajax: function(data, callback, settings) {
            var cols   = ['EmpleadoMunicipal.apellido1', 'EmpleadoMunicipal.cargo', 'Municipio.nombre', 'Departamento.nombre'];
            var params = $.param({
                page:   1 + (data.start / data.length),
                size:   data.length,
                order:  cols[data.order[0].column],
                sort:   data.order[0].dir,
                filter: data.search.value,
            });
            var url = '/api/empleado-municipal?' + params;
            $.getJSON(url, function(api) {
                var elements = [];
                api._embedded.list.forEach(function(element) {
                    var municipioLink = '<a href="/transparente/municipio/detalles/' + element.municipio_id + '">' + element.municipio + '</a>';
                    elements.push([element.nombre, element.cargo, municipioLink, element.departamento]);
                })
                var json = {
                    draw:            data.draw,
                    recordsTotal:    api.total_items,
                    recordsFiltered: api.total_items,
                    data:            elements
                };
                callback(json);
            });
        }
    });
});
</script>

<h1>Empleados municipales</h1>
<p>
    Listado de todos los empleados municipales importados proveidos por
    <a href="http://www.ojoconmipisto.com/">Ojo Con Mi Pisto</a>.
</p>
<table class="table data-table">
    <thead>
        <tr>
            <th>nombre</th>
            <th>cargo</th>
            <th>municipio</th>
            <th>departamento</th>
        </tr>
    </thead>
</table>