<?php
/**
 * Listar los empleados municipales
 */

/* @var $this \Zend\View\Renderer\PhpRenderer */

$this->layout()->setVariables([
    'title' => 'Empleados municipales',
]);
?>
<script type="text/javascript">
$(document).ready(function(){
    $('.data-table').dataTable({
        language: {url: '//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json'},
        processing: true,
        serverSide: true,
        ajax: function(data, callback, settings) {
            var cols   = ['EmpleadoMunicipal.apellido1', 'EmpleadoMunicipal.cargo', 'Municipio.nombre', 'Departamento.nombre'];
            var params = $.param({
                page:   1 + (data.start / data.length),
                size:   data.length,
                order:  cols[data.order[0].column],
                sort:   data.order[0].dir,
                filter: data.search.value,
            });
            var url = '/api/empleado-municipal?' + params;
            $.getJSON(url, function(api) {
                var elements = [];
                api._embedded.list.forEach(function(element) {
                    var municipioLink = '<a href="/transparente/municipio/detalles/' + element.municipio_id + '">' + element.municipio + '</a>';
                    elements.push([element.nombre, element.cargo, municipioLink, element.departamento]);
                })
                var json = {
                    draw:            data.draw,
                    recordsTotal:    api.total_items,
                    recordsFiltered: api.total_items,
                    data:            elements
                };
                callback(json);
            });
        }
    });
});
</script>

<p>
    Listado de todos los empleados municipales importados proveidos por
    <a href="http://www.ojoconmipisto.com/">Ojo Con Mi Pisto</a>.
</p>
<?=$this->partial('partial/dbcomprasdisclamer') ?>
<center>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- horizontal-content -->
    <ins class="adsbygoogle"
         style="display:inline-block;width:728px;height:90px"
         data-ad-client="ca-pub-4234050867741816"
         data-ad-slot="1596749955"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</center>
<table class="table data-table">
    <thead>
        <tr>
            <th>nombre</th>
            <th>cargo</th>
            <th>municipio</th>
            <th>departamento</th>
        </tr>
    </thead>
</table>
<?=$this->partial('partial/opendatadisclamer') ?>