<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Editar Domicilio';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('domicilios', array('action'=>'index'));?>">
		<span">Regresar</span>
	</a>
</p>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'domicilios',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

?>