<?php
/**
 * Listar el detalle del municipio
 */

/* @var $this Zend\View\Renderer\PhpRenderer */

$municipio = $this->municipio;
/* @var $municipio Transparente\Model\Entity\GeoMunicipio */

$representantes = $this->representantes;
?>
<style >
.empleado {float: left; height: 360px; width: 100%;}
.logo-partido {height: 100px; margin-right: 10px;}
.rep-legales {height: 16em; overflow: auto}

.dl-horizontal dt { width: 260px; }
.dl-horizontal dd { margin-left: 270px;}
</style>
<h1>Municipio: <?=$municipio->getNombre()?>, <?=$municipio->getDepartamento()->getNombre()?></h1>
<div class="row">
    <div class="col-sm-4">

        <p>Listado de los miembros del consejo municipal.</p>
        <p>
            Los miembros del consejo tienen poder de decición para contratar a los proveedores. Éste puede decidir darles el
            trabajo a sus familiares con quienes ya ha acordado un precio para repartirse las ganancias. Esto es ilegal, pero es
            difícil de encontrar; es por eso que buscamos listar los apellidos relacionados para encontrar estas posibles
            relaciónes entre familiares.
        </p>
    </div>
    <div class="col-sm-8">
        <iframe width="560" height="315" src="//www.youtube.com/embed/m-JozsD_IxQ?rel=0&end=50" style="border: none;"></iframe>
    </div>
</div>
<div class="row">
    <?php foreach($this->empleadosMunicipales as $empleado) :?>
    <div class="col-sm-6">
    <div class="panel panel-default empleado">
        <div class="panel-heading"><?=$empleado->getCargo()?></div>
            <div class="panel-body">
                <img class="pull-left logo-partido img-thumbnail"
                     title="<?=$empleado->getPartidoPolítico()->getNombre()?>"  alt="<?=$empleado->getPartidoPolítico()->getNombre()?>"
                     src="<?=$this->basePath()?>/Transparente/img/logos-partidos/<?=$empleado->getPartidoPolítico()->getIniciales()?>.svg"  />
                <h4><?=$empleado->getNombre()?></h4>
                <?php if ($representantes[$empleado->getId()]) :?>
                    <p>Apellidos en común con:</p>
                    <ul class="rep-legales">
                        <?php foreach($representantes[$empleado->getId()] as $representanteLegal) : /* @var $representanteLegal \Transparente\Model\Entity\RepresentanteLegal */?>
                            <li>
                                <a href="<?=$this->url()?>representante-legal/detalles/<?=$representanteLegal->getId()?>">
                                    <?=$representanteLegal->getNombre()?>
                                </a>
                            </li>
                        <?php endforeach ?>
                    </ul>
                <?php endif ?>
          </div>
    </div>
    </div>
    <?php endforeach ?>
</div>