<?php
/**
 * Listar los representantes legales
 */

/* @var $this Zend\View\Renderer\PhpRenderer */
?>
<script type="text/javascript">
$(document).ready(function(){
    $('.data-table').dataTable({
        language: {url: '//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json'},
        processing: true,
        serverSide: true,
        ajax: function(data, callback, settings) {
            var cols   = ['RepresentanteLegal.apellido1', 'RepresentanteLegal.nit', 'Proveedor.nombre'];
            var params = $.param({
                page:   1 + (data.start / data.length),
                size:   data.length,
                order:  cols[data.order[0].column],
                sort:   data.order[0].dir,
                filter: data.search.value,
            });
            var url = '/api/representante-legal?' + params;
            $.getJSON(url, function(api) {
                var elements = [];
                api._embedded.representante_legal.forEach(function(element) {
                    var nombres   = element.nombre1   + ' '  + element.nombre2;
                    var apellidos = element.apellido1 + ' '  + element.apellido2;
                    var nombre    = apellidos.trim()  + ', ' + nombres.trim();
                    var link = '<a href="/transparente/representante-legal/detalles/' + element.id + '">' + nombre + '</a>';
                    var proveedores = '<ul>';
                    element.proveedores.forEach(function(data) {
                        proveedores += '<li><a href="/transparente/proveedores/detalles/' + data.id + '">' + data.nombre + '</a></li>';
                    });
                    proveedores += '</ul>';
                    elements.push([link, element.nit, proveedores]);
                })
                var json = {
                    draw:            data.draw,
                    recordsTotal:    api.total_items,
                    recordsFiltered: api.total_items,
                    data:            elements
                };
                callback(json);
            });
        }
    });
});
</script>

<h1>Representantes legales</h1>
<p>
    Catálogo de representantes legales recopilados al importar los proveedores.
</p>
<center>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- horizontal-content -->
    <ins class="adsbygoogle"
         style="display:inline-block;width:728px;height:90px"
         data-ad-client="ca-pub-4234050867741816"
         data-ad-slot="1596749955"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</center>
<table class="table data-table">
    <thead>
        <tr>
            <th>nombre</th>
            <th class="text-right">nit</th>
            <th>repersenta al proveedor</th>
        </tr>
    </thead>
</table>

<?=$this->partial('partial/opendatadisclamer') ?>